### ISSUE TITLE
Rviz Seg Fault after Interactive Marker placed

### ISSUE THREAD

**Issue by grossmanlev** [bayesian-object-tracking/dbot_ros#1]
Hello,

I am trying to run your Gaussian tracker using Kinect v2 and ROS.  However, after placing the Interactive Marker onto the pointcloud in rviz, rviz quits with a seg fault.  I am not sure the root of this problem, but have you encountered this in your testing? (running ROS Kinetic on Ubuntu 16.04)

Thanks!

**Comment by cassinaj** [comment]
Hi!

we have developed and tested the tracking on ROS Indigo on Ubuntu 14.04.
Unfortunately, I have not tested the system on Ubuntu 16.04 using Kinetic.
Nevertheless, the Rviz issue sounds like an independent problem. It could
be that RVIZ is unable to load the mesh file or it is receiving an invalid
pose (e.g. potentially NAN values) causing rviz to crash.

Does the tracking keep running? You can check for the object topic
('rostopic echo' command) and see if the tracker is publishing reasonable
values.

Best,
Jan

**Comment by grossmanlev** [comment]
Hello, it does seem like it's just an Rviz issue, as the tracker does run, but it (particle tracker) is quite slow... much slower than the example (using just CPU).  I am using 100 particles and getting a message that I should reduce the number of particles because it's too slow.  Is this normal?

Also, when trying to make with Cuda 8.0, I am getting an "undefined reference to 'cudaGraphicsUnregisterResource'" in libdbot.so.  Any ideas how I can fix this?  Should I revert to an earlier distribution of CUDA?

Thanks!

**Comment by Gaoqinghong91** [comment]
I met same problem with Cuda 8.0 .do you resolve it now? 
thank you !

**Comment by jbohg** [comment]
It seems that the newest ROS packages have addressed the underlying RVIZ issue. dbot getting started was tested under 16.04 with kinetic and clicking on the interactive marker does not create a problem anymore.
