### ISSUE TITLE
is this suitable for any object that is in dynamic state? 

### ISSUE THREAD

**Issue by pkr97** [bayesian-object-tracking/dbot_ros#4]
hell all, hope you are doing well. 

I'm interested to use this package for tracking objects with depth image.  I have a depth sensor. I want to throw a cube or any solid object and track that using the depth image in ROS. is it possible to use this library for that kind of application?

Waiting for kind reply.

Cheers

Prasanna

**Comment by jbohg** [comment]
In principle this is possible. The bottleneck is the sampling rate of the camera sensor which is only 30Hz. The faster an object moves (for example when it is thrown), the larger the change from frame to frame and therefore the more difficult to hit the right pose with a sample. 

For now, the hyperparameters of the filter are tuned to work well for manipulation. For these dynamic movements, you may need to tune the process model accordingly.
