### ISSUE TITLE
Some questions on tracking the specificed object?

### ISSUE THREAD

**Issue by BIGJUN777** [bayesian-object-tracking/dbot_ros#7]
Hello! 
Firstly, I appreciate that you share your excellent work here. These day, I tried to use those pacakges in ROS to do something objects-tracking.Here I have some questions on tracking the specificed object?
    1.  When tracking the specified object, it seems that we need to set the original pose of the object.In practice, does it mean that we need to send the real pose of the object to the service to realize the tracking?
    2.   In practice, can I leavage this work to track multi-object?And how?
Looking for your response.Thx!

**Comment by honey-booboo** [comment]
Hi! Thanks for your interest in our work :)

1. May I point to the [getting started repo](https://github.com/bayesian-object-tracking/getting_started), which explains how to run in practice an object tracking example. This is the basic usage of the tracker. As you'll see, the initial pose is given through an interactive marker. The initial pose doesn't need to be perfect, but close enough. You can try it yourself to get a sense of how close.

It is also possible to programatically send an initial pose to an object tracking _service_, but that's more advance usage. (I'm not sure if your question was actually along those lines).

2. The same basic example should work with multiple objects by specifying multiple objects in the list of the yaml file. 

May I suggest that from now on you open different threads for different questions. If you run into problems, please always explain the behavior you obtain when running the getting-started example. 

Thanks!

**Comment by BIGJUN777** [comment]
Thanks!
